### ISSUE TITLE
BUG-02 / Pass IP case value is "-0"

### ISSUE THREAD

**Issue by ghost** [CrBast/KubeahChat#2]
BUG - 0002
Can enter without warning the value "-0" on the IP case. But when press START an error occured "Error PING". And crash the application.

![error](https://user-images.githubusercontent.com/31389439/30006230-25bb5aa6-90f4-11e7-9ea3-96f1d8237631.png)

**Comment by crbast** [comment]
The bug was been corrected "version 1.4.2"
